apiVersion: cloudformation.aws.upbound.io/v1beta1
kind: StackSet
metadata:
  annotations:
    meta.upbound.io/example-id: cloudformation/v1beta1/stackset
  labels:
    testing.upbound.io/example-name: blanketopscloudformation
  name: blanketops-cloudformation-stackset
spec:
  forProvider:
    administrationRoleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: AWSCloudFormationStackSetAdministrationRole
    parameters:
      VPCCidr: 10.0.0.0/16
    region: eu-north-1
    templateBody: >
      {
        "Parameters" : {
          "VPCCidr" : {
            "Type" : "String",
            "Default" : "10.0.0.0/16",
            "Description" : "Enter the CIDR block for the VPC. Default is 10.0.0.0/16."
          }
        },
        "Resources" : {
          "myVpc": {
            "Type" : "AWS::EC2::VPC",
            "Properties" : {
              "CidrBlock" : { "Ref" : "VPCCidr" },
              "Tags" : [
                {"Key": "Name", "Value": "Primary_CF_VPC"}
              ]
            }
          }
        }
      }
