apiVersion: autoscaling.aws.upbound.io/v1beta1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: autoscaling/v1beta1/policy
  labels:
    testing.upbound.io/example-name: blanketops-autoscaling-policy
  name: blanketops-autoscaling-policy
spec:
  forProvider:
    adjustmentType: ChangeInCapacity
    autoscalingGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-autoscaling-group
    cooldown: 300
    region: eu-north-1
    scalingAdjustment: 4
