apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: database
  namespace: dev
spec:
  tag: 686255954747.dkr.ecr.eu-north-1.amazonaws.com/blanketops-ecr-database-repository:develop
  serviceAccount: database-service-account
  builder:
    name: database-image-builder
    kind: Builder
  source:
    git:
      url: https://github.com/blanketops/blanketops-nginx-example.git
      revision: refs/heads/develop
