apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: microservice
  namespace: dev
spec:
  tag: 686255954747.dkr.ecr.eu-north-1.amazonaws.com/blanketops-ecr-microservice-repository:develop
  serviceAccount: microservice-service-account
  builder:
    name: microservice-image-builder
    kind: Builder
  source:
    git:
      url: git@github.com:blanketops/blanketops-nginx-example.git
      revision: refs/heads/develop
