apiVersion: backup.aws.upbound.io/v1beta1
kind: VaultLockConfiguration
metadata:
  name: blanketops-backup-vault-configuration
spec:
  forProvider:
    backupVaultNameSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-backup-vault
    changeableForDays: 3
    maxRetentionDays: 1200
    minRetentionDays: 7
    region: eu-north-1
