apiVersion: backup.aws.upbound.io/v1beta1
kind: VaultPolicy
metadata:
  name: example
spec:
  forProvider:
    backupVaultNameSelector:
      matchLabels:
        testing.upbound.io/example-name: vault
    policy: >-
      {
        "Version": "2012-10-17",
        "Id": "default",
        "Statement": [
          {
            "Sid": "default",
            "Effect": "Allow",
            "Principal": {
              "AWS": "*"
            },
            "Action": [
              "backup:DescribeBackupVault",
              "backup:DeleteBackupVault",
              "backup:PutBackupVaultAccessPolicy",
              "backup:DeleteBackupVaultAccessPolicy",
              "backup:GetBackupVaultAccessPolicy",
              "backup:StartBackupJob",
              "backup:GetBackupVaultNotifications",
              "backup:PutBackupVaultNotifications"
            ],
            "Resource": "arn:aws:backup:eu-north-1:609897127049:backup-vault:example-bucket-vault"
          }
        ]
      }
    region: eu-north-1
