apiVersion: backup.aws.upbound.io/v1beta1
kind: Plan
metadata:
  labels:
    testing.upbound.io/example-name: blanketops-backup-plan
  name: blanketops-backup-plan
spec:
  forProvider:
    advancedBackupSetting:
    - backupOptions:
        WindowsVSS: enabled
      resourceType: EC2
    name: test-random
    region: eu-north-1
    rule:
    - lifecycle:
      - deleteAfter: 14
      ruleName: up_example_backup_rule
      schedule: cron(0 12 * * ? *)
      targetVaultNameSelector:
        matchLabels:
          testing.upbound.io/example-name: vault
