apiVersion: backup.aws.upbound.io/v1beta1
kind: RegionSettings
metadata:
  name: blanketops-backup-region-settings
spec:
  forProvider:
    region: eu-north-1
    resourceTypeManagementPreference:
      DynamoDB: true
      EFS: true
    resourceTypeOptInPreference:
      Aurora: true
      DynamoDB: true
      EBS: true
      EC2: true
      EFS: true
      FSx: true
      Neptune: true
      RDS: true
      S3: true
      Storage Gateway: true
      VirtualMachine: true
