apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: localstack-aws-secret
      namespace: localstack
      key: creds
  endpoint:
    hostnameImmutable: true
    #TODO: add more services to this list, as needed
    services: [ iam, s3, sqs, sts, ec2, ecr, ecs, dynamodb ]
    url:
      type: Static
      static: http://localstack.localstack.svc.cluster.local:4566
  skip_credentials_validation: true
  skip_metadata_api_check: true
  skip_requesting_account_id: true
  s3_use_path_style: true
