---
apiVersion: batch.blanketops.co.za/v1alpha1
kind: Environment
metadata:
  name: car-sales-web-lamp-wamp-environment
  namespace: qa
spec:

  application:
    name: car-sales-web-lamp-wamp-application
    stack:
      name: lamp-wamp
      tier:
        name: backend
        programmingLanguageName: php

  builder:
    name: car-sales-web-lamp-wamp-build
    imageToBuild: public.ecr.aws/docker/library/httpd:latest
    scheduleType: automatic

  buildPipelines:
  - name: car-sales-web-lamp-wamp-build-and-push-pipeline
    tasks:
    - name: git-clone
    - name: build-and-push-to-registry

  capacity:
    scalingOperationName: car-sales-lamp-wamp-capacity-scaling-operation #
    scaling: car-sales-lamp-wamp-capacity-scaling #
    scalingGroupName: car-sales-aws-autoscaling-group #
    capacityProvider: car-sales-ecs-capacity-provider ##
    clusterCapacityProviders: car-sales-ecs-cluster-capacity-providers ##

  containerRegistries:
  - name: car-sales-ecr-microservice-repository
    imageTagMutability: MUTABLE

  deployment:
    name: car-sales-web-lamp-wamp-deployment
    strategy: rolling-upgrade #
    scheduleType: automatic #

  infrastructure:
    clusterName: car-sales-web-lamp-wamp-cluster #

  location: "EU"

  backend:
    name: car-sales-lamp-wamp-backend
    image: 686255954747.dkr.ecr.eu-north-1.amazonaws.com/car-sales-ecr-backend-repository:feature#hello-world
    containerPort: 9000
    size: 1

  database:
    name: car-sales-lamp-wamp-database
    image: 686255954747.dkr.ecr.eu-north-1.amazonaws.com/car-sales-ecr-database-repository:feature#hello-world
    containerPort: 3306
    size: 1
  frontend:
    name: car-sales-lamp-wamp-frontend
    image: 686255954747.dkr.ecr.eu-north-1.amazonaws.com/car-sales-ecr-frontend-repository:feature#hello-world
    containerPort: 8086
    size: 1
  webserver:
    name: car-sales-lamp-wamp-webserver
    image: 686255954747.dkr.ecr.eu-north-1.amazonaws.com/car-sales-ecr-webserver-repository:feature#hello-world
    containerPort: 8085
    size: 1

  namespace: qa
  service:
    name: github-message-dumper
    remoteSourceCodeRepositoryLink: https://github.com/blanketops/blanketops-nginx-example.git
    remoteSourceCodeRepositorySecretName: githubsecret
    githubSourceWebhook: githubsourcesample
    eventName:
    eventListerName: car-sales-microservice-tekton-event-listener

  packageApplicationPipelines:
  - name: car-sales-web-lamp-wamp-package-pipeline

  type: lamp-wamp
