apiVersion: iam.aws.upbound.io/v1beta1
kind: InstanceProfile
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/instanceprofile
  labels:
    testing.upbound.io/example-name: blanketops-iam-instance-profile
  name: blanketops-iam-instance-profile
spec:
  forProvider:
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-iam-role-with-inline-policy
