apiVersion: organizations.aws.upbound.io/v1beta1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: organizations/v1beta1/policyattachment
  labels:
    testing.upbound.io/example-name: blanketopsorganization
  name: blanketops-aws-organization-policy
spec:
  forProvider:
    content: |
      {
        "Version": "2012-10-17",
        "Statement": {
          "Effect": "Allow",
          "Action": "*",
          "Resource": "*"
        }
      }
    name: blanketops-aws-organization-policy
    region: eu-north-1
