apiVersion: organizations.aws.upbound.io/v1beta1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: organizations/v1beta1/account
  labels:
    testing.upbound.io/example-name: blanketopsorganization
  name: blanketops-aws-organization-account
spec:
  forProvider:
    email: <new-account-email>
    name: my_new_account
    region: eu-north-1
