apiVersion: ecs.aws.upbound.io/v1beta1
kind: CapacityProvider
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/capacityprovider
  labels:
    testing.upbound.io/example-name: blanketops-ecs-capacity-provider
  name: blanketops-ecs-capacity-provider
spec:
  forProvider:
    autoScalingGroupProvider:
    - autoScalingGroupArnSelector:
        matchLabels:
          testing.upbound.io/example-name: blanketops-autoscaling-group
      managedScaling:
      - maximumScalingStepSize: 1000
        minimumScalingStepSize: 1
        status: ENABLED
        targetCapacity: 10
      managedTerminationProtection: DISABLED
    region: eu-north-1
