apiVersion: codecommit.aws.upbound.io/v1beta1
kind: ApprovalRuleTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: codecommit/v1beta1/approvalruletemplate
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    content: >
      {
          "Version": "2018-11-08",
          "DestinationReferences": ["refs/heads/master"],
          "Statements": [{
              "Type": "Approvers",
              "NumberOfApprovalsNeeded": 2,
              "ApprovalPoolMembers": ["arn:aws:sts::${data.aws_account_id}:assumed-role/CodeCommitReview/*"]
          }]
      }
    description: This is an example approval rule template
    region: eu-north-1
