apiVersion: codecommit.aws.upbound.io/v1beta1
kind: Trigger
metadata:
  annotations:
    meta.upbound.io/example-id: codecommit/v1beta1/trigger
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: eu-north-1
    repositoryNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example-trigger
    trigger:
    - destinationArnSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      events:
      - all
      name: all
