apiVersion: ec2.aws.upbound.io/v1beta1
kind: DefaultSubnet
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/defaultsubnet
  labels:
    testing.upbound.io/example-name: blanketops-ec2-default-subnet
  name: blanketops-ec2-default-subnet
spec:
  forProvider:
    availabilityZone: eu-north-1a
    region: eu-north-1
    tags:
      Name: Default subnet for eu-north-1a
