apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: blanknetops-ec2-internet-gateway-routegw
spec:
  forProvider:
    region: eu-north-1
    tags:
      Name: main
    vpcIdRef:
      name: route-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: blanknetops-ec2-internet-gateway
spec:
  forProvider:
    region: eu-north-1
    tags:
      Name: main
    vpcIdRef:
      name: sample-vpc
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/defaultroutetable
  labels:
    testing.upbound.io/example-name: blanknetops-ec2-internet-gateway
  name: blanknetops-ec2-internet-gateway
spec:
  forProvider:
    region: eu-north-1
    tags:
      Name: main
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta2/route
  name: blanknetops-ec2-internet-gateway
spec:
  forProvider:
    region: eu-north-1
    tags:
      Name: main
    vpcIdRef:
      name: route-vpc
