apiVersion: ec2.aws.upbound.io/v1beta1
kind: TransitGatewayConnect
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/transitgatewayconnect
  labels:
    testing.upbound.io/example-name: blanketops-ec2-transit-gateway-connect
  name: blanketops-ec2-transit-gateway-connect
spec:
  forProvider:
    region: eu-north-1
    transitGatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    transportAttachmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
