apiVersion: ec2.aws.upbound.io/v1beta1
kind: NetworkInterfaceAttachment
metadata:
  labels:
    testing.upbound.io/example-name: blanketops-ec2-network-interface-attachment
  name: blanketops-ec2-network-interface-attachment
spec:
  forProvider:
    deviceIndex: 1
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    networkInterfaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test2
    region: eu-north-1
