apiVersion: ec2.aws.upbound.io/v1beta1
kind: DefaultVPC
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/defaultvpc
  labels:
    testing.upbound.io/example-name: blanketops-ec2-default-vpc
  name: blanketops-ec2-default-vpc
spec:
  forProvider:
    region: eu-north-1
    tags:
      Name: BlanketOps Default VPC
