apiVersion: ec2.aws.upbound.io/v1beta1
kind: TransitGatewayPolicyTable
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/transitgatewaypolicytable
  labels:
    testing.upbound.io/example-name: blanketops-ec2-transit-gateway-policy-table
  name: blanketops-ec2-transit-gateway-policy-table
spec:
  forProvider:
    region: eu-north-1
    tags:
      Name: Example Policy Table
    transitGatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-ec2-transit-gateway-for-policy-table
