apiVersion: ec2.aws.upbound.io/v1beta1
kind: ManagedPrefixListEntry
metadata:
  labels:
    testing.upbound.io/example-name: blanketops-ec2-managed-prefix-list-entry
  name: blanketops-ec2-managed-prefix-list-entry
spec:
  forProvider:
    cidr: 10.0.1.0/24
    description: Primary
    prefixListIdSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-ec2-managed-prefix-list
    region: eu-north-1
