apiVersion: ec2.aws.upbound.io/v1beta1
kind: EBSSnapshot
metadata:
  labels:
    testing.upbound.io/example-name: blanketops-ec2-ebs-snapshot
  name: blanketops-ec2-ebs-snapshot
spec:
  forProvider:
    region: eu-north-1
    tags:
      Name: BlanketOps_snap
    volumeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-ec2-ebs-volume
