apiVersion: ec2.aws.upbound.io/v1beta2
kind: Route
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta2/route
  name: blanketops-ec2-route
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdRef:
      name: routegw
    region: eu-north-1
    routeTableIdRef:
      name: blanketops-ec2-route-table-route
