apiVersion: ec2.aws.upbound.io/v1beta1
kind: EBSDefaultKMSKey
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/ebsdefaultkmskey
  labels:
    testing.upbound.io/example-name: blanketops-ec2-ebs-default-kms-key
  name: blanketops-ec2-ebs-default-kms-key
spec:
  forProvider:
    keyArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: eu-north-1
