apiVersion: ec2.aws.upbound.io/v1beta1
kind: NetworkInsightsPath
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/networkinsightsanalysis
  labels:
    testing.upbound.io/example-name: blanketops-ec2-network-insights-path
  name: blanketops-ec2-network-insights-path
spec:
  forProvider:
    destinationSelector:
      matchLabels:
        testing.upbound.io/example-name: destination
    protocol: tcp
    region: eu-north-1
    sourceSelector:
      matchLabels:
        testing.upbound.io/example-name: source
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: NetworkInsightsPath
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/networkinsightspath
  labels:
    testing.upbound.io/example-name: blanketops-ec2-network-insights-path-test
  name: blanketops-ec2-network-insights-path-test
spec:
  forProvider:
    destinationSelector:
      matchLabels:
        testing.upbound.io/example-name: destination
    protocol: tcp
    region: eu-north-1
    sourceSelector:
      matchLabels:
        testing.upbound.io/example-name: source
