apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPCIpamPoolCidr
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/vpcipampoolcidrallocation
  labels:
    testing.upbound.io/example-name: blanketops-ec2-vpc-ipam-pool-cidr-for-allocation
  name: blanketops-ec2-vpc-ipam-pool-cidr-for-allocation
spec:
  forProvider:
    cidr: 172.2.0.0/16
    ipamPoolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-ec2-vpc-ipam-pool
    region: eu-north-1
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPCIpamPoolCidr
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/vpc-ipampool
  labels:
    testing.upbound.io/example-name: blanketops-ec2-vpc-ipam-pool-cidr-for-ipam-pool
  name: blanketops-ec2-vpc-ipam-pool-cidr-for-ipam-pool
spec:
  forProvider:
    cidr: 172.2.0.0/16
    ipamPoolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-ec2-vpc-ipam-pool
    region: eu-north-1
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPCIpamPoolCidr
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/vpcipampoolcidr
  labels:
    testing.upbound.io/example-name: blanketops-ec2-vpc-ipam-pool-cidr-for-ipam-pool-cidr
  name: blanketops-ec2-vpc-ipam-pool-cidr-for-ipam-pool-cidr
spec:
  forProvider:
    cidr: 172.2.0.0/16
    ipamPoolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-ec2-vpc-ipam-pool
    region: eu-north-1
