apiVersion: ec2.aws.upbound.io/v1beta1
kind: NetworkACL
metadata:
  name: blanketops-ec2-network-acl
spec:
  forProvider:
    region: eu-north-1
    tags:
      Name: main
    vpcIdRef:
      name: example
