apiVersion: ec2.aws.upbound.io/v1beta1
kind: TransitGatewayMulticastDomain
metadata:
  labels:
    testing.upbound.io/example-name: blanketops-ec2-transit-gateway-multicast-domain
  name: blanketops-ec2-transit-gateway-multicast-domain
spec:
  forProvider:
    region: eu-north-1
    staticSourcesSupport: enable
    tags:
      Name: Transit_Gateway_Multicast_Domain_Example
    transitGatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
