apiVersion: ec2.aws.upbound.io/v1beta1
kind: CarrierGateway
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/carriergateway
  labels:
    testing.upbound.io/example-name: blanketops-ec2-carrier-gateway
  name: blanketops-ec2-carrier-gateway
spec:
  forProvider:
    region: eu-north-1
    tags:
      Name: blanketops-ec2-carrier-gateway
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
