apiVersion: ec2.aws.upbound.io/v1beta1
kind: MainRouteTableAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/mainroutetableassociation
  labels:
    testing.upbound.io/example-name: blanketops-ec2-main-route-table-association
  name: blanketops-ec2-main-route-table-association
spec:
  forProvider:
    region: eu-north-1
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: table
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: route-vpc #main-route-table-association
