apiVersion: ec2.aws.upbound.io/v1beta1
kind: SpotFleetRequest
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/spotfleetrequest
  labels:
    testing.upbound.io/example-name: blanketops-ec2-spot-fleet-request
  name: blanketops-ec2-spot-fleet-request
spec:
  forProvider:
    allocationStrategy: capacityOptimized
    iamFleetRole: arn:aws:iam::${data.aws_account_id}:role/aws-service-role/spotfleet.amazonaws.com/AWSServiceRoleForEC2SpotFleet
    launchSpecification:
    - ami: ami-0bdb828fd58c52235
      iamInstanceProfileArnSelector:
        matchLabels:
          testing.upbound.io/example-name: blanketops-iam-instance-profile
      instanceType: t2.xlarge
      placementTenancy: dedicated
      spotPrice: "2.793"
    region: eu-north-1
    spotPrice: "0.03"
    targetCapacity: 6
