apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPNConnection
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/vpnconnectionroute
  labels:
    testing.upbound.io/example-name: blanketops-ec2-for-vpn-connection-route
  name: blanketops-ec2-for-vpn-connection-route
spec:
  forProvider:
    customerGatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: customer_gateway
    region: eu-north-1
    staticRoutesOnly: true
    type: ipsec.1
    vpnGatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpn_gateway
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPNConnection
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/vpnconnection
  labels:
    testing.upbound.io/example-name: blanketops-ec2-for-vpn-connection
  name: blanketops-ec2-for-vpn-connection
spec:
  forProvider:
    customerGatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: eu-north-1
    transitGatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    typeSelector:
      matchLabels:
        testing.upbound.io/example-name: example
