apiVersion: ec2.aws.upbound.io/v1beta1
kind: TransitGatewayMulticastGroupMember
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/transitgatewaymulticastgroupmember
  labels:
    testing.upbound.io/example-name: blanketops-ec2-transit-gateway-multicast-group-member
  name: blanketops-ec2-transit-gateway-multicast-group-member
spec:
  forProvider:
    groupIpAddress: 224.0.0.1
    networkInterfaceIdRef:
      name: sample-ni
    region: eu-north-1
    transitGatewayMulticastDomainIdRef:
      name: domain
