apiVersion: ec2.aws.upbound.io/v1beta1
kind: NetworkInsightsAnalysis
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/networkinsightsanalysis
  labels:
    testing.upbound.io/example-name: blanketops-ec2-network-insights-analysis
  name: blanketops-ec2-network-insights-analysis
spec:
  forProvider:
    networkInsightsPathIdSelector:
      matchLabels:
        testing.upbound.io/example-name: path
    region: eu-north-1
