apiVersion: ec2.aws.upbound.io/v1beta1
kind: AMICopy
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/amicopy
  labels:
    testing.upbound.io/example-name: blanketops-ec2-ami-copy
  name: blanketops-ec2-ami-copy
spec:
  forProvider:
    description: BlanketOps AMI Copy
    name: blanketops-ami-device
    region: eu-north-1
    sourceAmiIdSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-ec2-ami
    sourceAmiRegion: eu-north-1
    tags:
      Name: BlanketOps
