apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPCEndpointSecurityGroupAssociation
metadata:
  labels:
    testing.upbound.io/example-name: blanketops-ec2-vpc-endpoint-security-group-association
  name: blanketops-ec2-vpc-endpoint-security-group-association
spec:
  forProvider:
    region: eu-north-1
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: securitygroup1
    vpcEndpointIdSelector:
      matchLabels:
        testing.upbound.io/example-name: ec2
