apiVersion: aws.platform.upbound.io/v1alpha1
kind: XNetwork
metadata:
  annotations:
    render.crossplane.io/composition-path: apis/gotpl/composition.yaml
    render.crossplane.io/function-path: examples/functions.yaml
  name: configuration-aws-network
spec:
  parameters:
    id: configuration-aws-network
    region: eu-north-1
    subnets:
    - availabilityZone: eu-north-1a
      cidrBlock: 192.168.0.0/18
      type: public
    - availabilityZone: eu-north-1b
      cidrBlock: 192.168.64.0/18
      type: public
    - availabilityZone: eu-north-1a
      cidrBlock: 192.168.128.0/18
      type: private
    - availabilityZone: eu-north-1b
      cidrBlock: 192.168.192.0/18
      type: private
    vpcCidrBlock: 192.168.0.0/16
