apiVersion: ec2.aws.upbound.io/v1beta1
kind: NetworkInterface
metadata:
  labels:
    testing.upbound.io/example-name: blanketops-ecs-network-interface
  name: blanketops-ecs-network-interface
spec:
  forProvider:
    region: eu-north-1
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketopsec2

# apiVersion: ec2.aws.upbound.io/v1beta1
# kind: NetworkInterface
# metadata:
#   annotations:
#     meta.upbound.io/example-id: ec2/v1beta2/instance
#   labels:
#     testing.upbound.io/example-name: sample-instance
#   name: sample-instance
# spec:
#   forProvider:
#     privateIps:
#     - 172.16.10.100
#     region: eu-north-1
#     subnetIdSelector:
#       matchLabels:
#         testing.upbound.io/example-name: sample-instance
---

