apiVersion: sns.aws.upbound.io/v1beta1
kind: TopicSubscription
metadata:
  annotations:
    meta.upbound.io/example-id: sns/v1beta1/topicsubscription
  labels:
    testing.upbound.io/example-name: blanketops-sns-topic-subscription
  name: blanketops-sns-topic-subscription
spec:
  forProvider:
    endpointSelector:
      matchLabels:
        testing.upbound.io/example-name: sns # need endpoint
    protocol: sqs
    region: eu-north-1
    topicArnSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-sns-topic
