apiVersion: sns.aws.upbound.io/v1beta1
kind: PlatformApplication
metadata:
  annotations:
    meta.upbound.io/example-id: sns/v1beta1/platformapplication
  labels:
    testing.upbound.io/example-name: blanketops-sns-platform
  name: blanketops-sns-platform
spec:
  forProvider:
    platform: GCM
    platformCredentialSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    region: eu-north-1
