---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: environments.batch.blanketops.co.za
spec:
  group: batch.blanketops.co.za
  names:
    kind: Environment
    plural: environments
  claimNames:
    kind: EnvironmentClaim
    plural: environmentclaim
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              deployment:
                type: object
                properties:
                  name:
                    type: string
                  strategy:
                    type: string
                  scheduleType:
                    type: string
              infrastructure:
                type: object
                properties:
                  clusterName:
                    type: string
              containerRegistries:
                type: array
                items:
                  type: object
                  name:
                    type: string
                  imageTagMutability:
                    type: string
              capacity:
                type: object
                properties:
                  scalingOperationName:
                    type: string
                  scaling:
                    type: string
                  scalingGroupName:
                    type: string
                  capacityProvider:
                    type: string
                  clusterCapacityProviders:
                    type: string
              application:
                type: object
                properties:
                  name:
                    type: string
                  stack:
                    type: object
                    properties:
                      name:
                        type: string
                      tier:
                        type: object
                        properties:
                          name:
                            type: string
                          programmingLanguageName:
                            type: string
              location:
                type: string
                oneOf:
                - pattern: '^EU$'
                - pattern: '^US$'
              namespace:
                type: string
                oneOf:
                - pattern: '^dev$'
                - pattern: '^qa$'
                - pattern: '^prd$'
              type:
                type: string
                oneOf:
                - pattern: '^microservices$'
                - pattern: '^single$'
                - pattern: '^mobile$'
                - pattern: '^lamp-wamp$'
              backend:
                type: object
                properties:
                  name:
                    type: string
                  image:
                    type: string
                  size:
                    type: integer
                required:
                - name
                - size
                - image
              database:
                type: object
                properties:
                  name:
                    type: string
                  image:
                    type: string
                  size:
                    type: integer
                required:
                - name
                - size
                - image
              microservices:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    image:
                      type: string
                    size:
                      type: integer
                  required:
                  - name
                  - size
                  - image
              frontend:
                type: object
                properties:
                  name:
                    type: string
                  image:
                    type: string
                  size:
                    type: integer
                required:
                - name
                - size
                - image
              webserver:
                type: object
                properties:
                  name:
                    type: string
                  image:
                    type: string
                  size:
                    type: integer
                required:
                - name
                - size
                - image
              release:
                type: object
                properties:
                  name:
                    type: string
                  number:
                    type: integer
                  isReleased:
                    type: boolean
                  dateReleased:
                    type: string
                  deployedBranch:
                    type: string
                  rollback:
                    type: object
                    properties:
                      releaseName:
                        type: string
                      isEnabled:
                        type: boolean
                      releaseTag:
                        type: string

            required:
            - location
            - namespace
            - type
