---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: car-sales-web-microservice-composition
spec:
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: car-sales-ecr-microservice-repository #containerRegistries
        base:
          apiVersion: ecr.aws.upbound.io/v1beta1
          kind: Repository
          metadata:
            name: car-sales-ecr-microservice-repository
          spec:
            forProvider:
              imageTagMutability: MUTABLE
              region: eu-north-1
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.location"
          toFieldPath: "spec.forProvider.region"
          transforms:
          - type: map
            map:
              EU: "eu-north-1"
              US: "us-east-2"
      - name: car-sales-ecs-microservice-cluster #infrastructure, #private cluster, 
        base:
          apiVersion: ecs.aws.upbound.io/v1beta1
          kind: Cluster
          metadata:
            name: car-sales-ecs-microservice-cluster
          spec:
            forProvider:
              region: eu-north-1
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.location"
          toFieldPath: "spec.forProvider.region"
          transforms:
          - type: map
            map:
              EU: "eu-north-1"
              US: "us-east-2"
      - name: car-sales-ecs-microservice-cluster-public
        base:
          apiVersion: ecrpublic.aws.upbound.io/v1beta1
          kind: Repository
          metadata:
            name: car-sales-ecs-microservice-cluster-public
          spec:
            forProvider:
              catalogData:
              - aboutText: About Text
                architectures:
                - ARM
              description: Car Sales ECS Microservice Cluster Public
              operatingSystems:
              - Linux
              usageText: Usage Text
              region: eu-north-1
              providerConfigRef:
                name: default
      - name: microservice #Environment Type, spec
        base:
          apiVersion: ecs.aws.upbound.io/v1beta1
          kind: TaskDefinition
          metadata:
            name: car-sales-ecs-taskdefinition-microservice
          spec:
            forProvider:
              containerDefinitions: |-
                [
                  {
                    "name": "microservice",
                    "image": "public.ecr.aws/docker/library/httpd:latest",
                    "cpu": "256"
                    "executionRoleArn": "arn:aws:iam::686255954747:role/ecsTaskRole"
                    "memory": "512"
                    "networkMode": "awsvpc"
                    "runtimePlatform": { "operatingSystemFamily": "LINUX" }
                    "requiresCompatibilities": [ "FARGATE" ]
                    "portMappings": [
                      {
                        "containerPort": 80,
                        "hostPort": 80,
                        "protocol": "tcp"
                      }
                    ],
                    "essential": true,
                    "entryPoint": [
                       "sh",
                       "-c"
                    ],
                    "command": [
                      "/bin/sh -c \"echo '<html> <head> <title>Amazon ECS Sample App</title><style>body {margin-top: 40px; background-color: #333;} </style></head><body> <div style=color:white;text-align:center> <h1>Amazon ECS Sample App</h1> <h2>Congratulations!</h2> <p>Your application is now running on a container in Amazon ECS.</p> </div></body></html>'>/usr/local/apache2/htdocs/index.html && httpd-foreground\""
                    ]
                  }
                ]
              family: car-sales-ecs-taskdefinition-microservice
              region: eu-north-1

        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.location"
          toFieldPath: "spec.forProvider.region"
          transforms:
          - type: map
            map:
              EU: "eu-north-1"
              US: "us-east-2"

      - name: car-sales-ecs-microservice-service # deployment
        base:
          apiVersion: ecs.aws.upbound.io/v1beta1
          kind: Service
          metadata:
            name: car-sales-ecs-microservice-service
          spec:
            forProvider:
              cluster: car-sales-ecs-microservice-cluster
              launchType: EC2
              propagateTags: TASK_DEFINITION
              region: eu-north-1
              taskDefinitionSelector:
                matchLabels:
                  testing.upbound.io/example-name: car-sales-ecs-taskdefinition-microservice:1
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.location"
          toFieldPath: "spec.forProvider.region"
          transforms:
          - type: map
            map:
              EU: "eu-north-1"
              US: "us-east-2"
  compositeTypeRef:
    apiVersion: batch.blanketops.co.za/v1alpha1
    kind: Environment
