apiVersion: compute.azure.upbound.io/v1beta1
kind: SharedImage
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/sharedimage
  labels:
    testing.upbound.io/example-name: examplesharedimage
  name: examplesharedimage
spec:
  forProvider:
    galleryNameSelector:
      matchLabels:
        testing.upbound.io/example-name: sharedimageig
    identifier:
    - offer: OfferName
      publisher: PublisherName
      sku: ExampleSku
    location: West Europe
    osType: Linux
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: sharedimage-rg
