apiVersion: compute.azure.upbound.io/v1beta1
kind: DiskEncryptionSet
metadata:
  name: example
spec:
  forProvider:
    identity:
    - type: SystemAssigned
    keyVaultKeyId: https://yyy-example-keyvault.vault.azure.net/keys/yyppdd-example-key/0cdfea4ef85045b0a3a8ca539f6a311c
    location: West Europe
    resourceGroupNameRef:
      name: example-compute
