apiVersion: compute.azure.upbound.io/v1beta1
kind: LinuxVirtualMachineScaleSet
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/linuxvirtualmachinescaleset
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    adminSshKey:
    - publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+wWK73dCr+jgQOAxNsHAnNNNMEMWOHYEccp6wJm2gotpr9katuF/ZAdou5AaW1C61slRkHRkpRRX9FA9CYBiitZgvCCz+3nWNN7l/Up54Zps/pHWGZLHNJZRYyAB6j5yVLMVHIHriY49d/GZTZVNB8GoJv9Gakwc/fuEZYYl4YDFiGMBP///TzlI4jhiJzjKnEvqPFki5p2ZRJqcbCiF4pJrxUQR/RXqVFQdbRLZgYfJ8xGB878RENq3yQ39d8dVOkq4edbkzwcUmwwwkYVPIoDGsYLaRHnG+To7FvMeyO7xDVQkMKzopTQV8AuKpyvpqu0a9pWOMaiCyDytO7GGN you@me.com
      username: adminuser
    adminUsername: adminuser
    instances: 1
    location: West Europe
    networkInterface:
    - ipConfiguration:
      - name: internal
        primary: true
        subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: internal
      name: example
      primary: true
    osDisk:
    - caching: ReadWrite
      storageAccountType: Standard_LRS
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku: Standard_F2
    sourceImageReference:
    - offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
      version: latest
