apiVersion: compute.azure.upbound.io/v1beta1
kind: VirtualMachineExtension
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/virtualmachineextension
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    publisher: Microsoft.Azure.Extensions
    settings: |2
       {
        "commandToExecute": "hostname && uptime"
       }
    tags:
      environment: Production
    type: CustomScript
    typeHandlerVersion: "2.0"
    virtualMachineIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
