apiVersion: compute.azure.upbound.io/v1beta1
kind: WindowsVirtualMachineScaleSet
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/windowsvirtualmachinescaleset
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    adminPasswordSecretRef:
      key: password
      name: example-secret
      namespace: upbound-system
    adminUsername: adminuser
    instances: 1
    location: West Europe
    networkInterface:
    - ipConfiguration:
      - name: internal
        primary: true
        subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: internal
      name: example
      primary: true
    osDisk:
    - caching: ReadWrite
      storageAccountType: Standard_LRS
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku: Standard_F2
    sourceImageReference:
    - offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: 2016-Datacenter-Server-Core
      version: latest
