apiVersion: compute.azure.upbound.io/v1beta1
kind: SharedImageGallery
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/sharedimage
  labels:
    testing.upbound.io/example-name: sharedimageig
  name: sharedimageig
spec:
  forProvider:
    description: Shared images and things.
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: sharedimage-rg
    tags:
      Hello: There
      World: Example
---
apiVersion: compute.azure.upbound.io/v1beta1
kind: SharedImageGallery
metadata:
  name: example
spec:
  forProvider:
    description: Shared images and things.
    location: West Europe
    resourceGroupNameRef:
      name: example-compute
    tags:
      Hello: There
      World: Example
---
apiVersion: compute.azure.upbound.io/v1beta1
kind: SharedImageGallery
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/galleryapplication
  labels:
    testing.upbound.io/example-name: galleryapplicationig
  name: galleryapplicationig
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: galleryapplication-rg

---
apiVersion: compute.azure.upbound.io/v1beta1
kind: SharedImageGallery
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/galleryapplicationversion
  labels:
    testing.upbound.io/example-name: galleryappversiongallery
  name: galleryappversiongallery
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: galleryappversionrg
