apiVersion: compute.azure.upbound.io/v1beta1
kind: ManagedDisk
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/snapshot
  labels:
    testing.upbound.io/example-name: example
  name: example-managed-disk
spec:
  forProvider:
    createOption: Empty
    diskSizeGb: 10
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    storageAccountType: Standard_LRS
---
apiVersion: compute.azure.upbound.io/v1beta1
kind: ManagedDisk
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/manageddisksastoken
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    createOption: Empty
    diskSizeGb: 1
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: manageddisk
    storageAccountType: Standard_LRS
---
apiVersion: compute.azure.upbound.io/v1beta1
kind: ManagedDisk
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/manageddisksastoken
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    createOption: Empty
    diskSizeGb: 1
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: manageddisk
    storageAccountType: Standard_LRS
---
apiVersion: compute.azure.upbound.io/v1beta1
kind: ManagedDisk
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/virtualmachinedatadiskattachment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    createOption: Empty
    diskSizeGb: 10
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    storageAccountType: Standard_LRS
---
apiVersion: compute.azure.upbound.io/v1beta1
kind: ManagedDisk
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/manageddisk
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    createOption: Empty
    diskSizeGb: 1
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    storageAccountType: Standard_LRS
    tags:
      environment: staging
