apiVersion: compute.azure.upbound.io/v1beta1
kind: Image
metadata:
  name: example
spec:
  forProvider:
    location: West Europe
    osDisk:
    - blobUri: uri_here
      osState: Generalized
      osType: Linux
      sizeGb: 30
    resourceGroupNameRef:
      name: example-compute
