apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: simple-app.corp.com.1.0.0
spec:
  refName: simple-app.corp.com
  version: 1.0.0
  releaseNotes: |
    Initial release of the simple app package    
  template:
    spec:
fetch:
- imgpkgBundle:
    image: index.docker.io/k8slt/kctrl-example-pkg@sha256:8ffa7f9352149dba1d539d0006b38eda357917edcdd39b82497a61dab2c27b75
template:
- ytt:
    paths:
    - config/
- kbld:
    paths:
    - .imgpkg/images.yml
    - '-'
deploy:
- kapp: {}
  valuesSchema:
    openAPIv3:
title: simple-app.corp.com values schema
examples:
- svc_port: 80
  app_port: 80
  hello_msg: stranger
properties:
  svc_port:
    type: integer
    description: Port number for the service.
    default: 80
    examples:
    - 80
  app_port:
    type: integer
    description: Target port for the application.
    default: 80
    examples:
    - 80
  hello_msg:
    type: string
    description: Name used in hello message from app when app is pinged.
    default: stranger
    examples:
    - stranger
