apiVersion: elb.aws.upbound.io/v1beta1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: elb/v1beta1/backendserverpolicy
  labels:
    testing.upbound.io/example-name: blanketops-elb-policy
  name: blanketops-elb-policy
spec:
  forProvider:
    loadBalancerNameSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops
    policyAttribute:
    - name: PublicKeyPolicyName
      valueSelector:
        matchLabels:
          testing.upbound.io/example-name: blanketops-ca-pubkey-policy
    policyName: blanketops-root-ca-backend-auth-policy
    policyTypeName: BackendServerAuthenticationPolicyType
    region: eu-north-1
