apiVersion: elb.aws.upbound.io/v1beta1
kind: LBSSLNegotiationPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: elb/v1beta1/lbsslnegotiationpolicy
    upjet.upbound.io/manual-intervention: Depends on ELB with a manual intervention
  labels:
    testing.upbound.io/example-name: blanketops-elb-lbssl-negotiation-policy
  name: blanketops-elb-lbssl-negotiation-policy
spec:
  forProvider:
    attribute:
    - name: Protocol-TLSv1
      value: "false"
    - name: Protocol-TLSv1.1
      value: "false"
    - name: Protocol-TLSv1.2
      value: "true"
    - name: Server-Defined-Cipher-Order
      value: "true"
    - name: ECDHE-RSA-AES128-GCM-SHA256
      value: "true"
    - name: AES128-GCM-SHA256
      value: "true"
    - name: EDH-RSA-DES-CBC3-SHA
      value: "false"
    lbPort: 443
    loadBalancerSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-elb-lb
    name: blanketops-elb-lbssl-negotiation-policy
    region: eu-north-1
