apiVersion: cloudfront.aws.upbound.io/v1beta1
kind: Distribution
metadata:
  annotations:
    meta.upbound.io/example-id: cloudfront/v1beta1/distribution
  labels:
    testing.upbound.io/example-name: blanketops-cloudfront-distribution
  name: blanketops-cloudfront-distribution
spec:
  forProvider:
    comment: BlanketOps CloudFront Distribution
    defaultCacheBehavior:
    - allowedMethods:
      - DELETE
      - GET
      - HEAD
      - OPTIONS
      - PATCH
      - POST
      - PUT
      cachedMethods:
      - GET
      - HEAD
      defaultTtl: 3600
      forwardedValues:
      - cookies:
        - forward: none
        queryString: false
      maxTtl: 86400
      minTtl: 0
      targetOriginId: customOrigin
      viewerProtocolPolicy: allow-all
    defaultRootObject: index.html
    enabled: true
    isIpv6Enabled: true
    orderedCacheBehavior:
    - allowedMethods:
      - GET
      - HEAD
      - OPTIONS
      cachedMethods:
      - GET
      - HEAD
      - OPTIONS
      compress: true
      defaultTtl: 86400
      forwardedValues:
      - cookies:
        - forward: none
        headers:
        - Origin
        queryString: false
      maxTtl: 31536000
      minTtl: 0
      pathPattern: /content/immutable/*
      targetOriginId: customOrigin
      viewerProtocolPolicy: redirect-to-https
    - allowedMethods:
      - GET
      - HEAD
      - OPTIONS
      cachedMethods:
      - GET
      - HEAD
      compress: true
      defaultTtl: 3600
      forwardedValues:
      - cookies:
        - forward: none
        queryString: false
      maxTtl: 86400
      minTtl: 0
      pathPattern: /content/*
      targetOriginId: customOrigin
      viewerProtocolPolicy: redirect-to-https
    origin:
    - customOriginConfig:
      - httpPort: 80
        httpsPort: 443
        originKeepaliveTimeout: 5
        originProtocolPolicy: https-only
        originReadTimeout: 10
        originSslProtocols:
        - TLSv1.2
      domainName: app.my.cloud
      originId: customOrigin
    priceClass: PriceClass_200
    region: eu-north-1
    restrictions:
    - geoRestriction:
      - locations:
        - US
        - CA
        - GB
        - DE
        restrictionType: whitelist
    tags:
      Environment: production
    viewerCertificate:
    - cloudfrontDefaultCertificate: true
