apiVersion: cloudfront.aws.upbound.io/v1beta1
kind: OriginRequestPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: cloudfront/v1beta1/originrequestpolicy
  name: blanketops-cloudfront-origin-request-policy
spec:
  forProvider:
    comment: example comment
    cookiesConfig:
    - cookieBehavior: whitelist
      cookies:
      - items:
        - example
    headersConfig:
    - headerBehavior: whitelist
      headers:
      - items:
        - example
    queryStringsConfig:
    - queryStringBehavior: whitelist
      queryStrings:
      - items:
        - example
    region: eu-north-1
