apiVersion: cloudfront.aws.upbound.io/v1beta1
kind: RealtimeLogConfig
metadata:
  labels:
    testing.upbound.io/example-name: realtimelogconfig
  name: example
spec:
  forProvider:
    endpoint:
    - kinesisStreamConfig:
      - roleArnSelector:
          matchLabels:
            testing.upbound.io/example-name: realtimelogconfig
        streamArnSelector:
          matchLabels:
            testing.upbound.io/example-name: realtimelogconfig
      streamType: Kinesis
    fields:
    - timestamp
    - c-ip
    name: example-random
    region: eu-north-1
    samplingRate: 75
