apiVersion: pt.fn.crossplane.io/v1beta1
kind: Resources
resources:
- name: backend
  base:
    apiVersion: ecs.aws.upbound.io/v1beta1
    kind: TaskDefinition
    metadata:
      name: car-sales-ecs-taskdefinition-backend
    spec:
      forProvider:
        containerDefinitions: |-
          [
            {
              "name": "backend",
              "image": "686255954747.dkr.ecr.eu-north-1.amazonaws.com/car-sales-ecr-lamp-wamp-repository:develop",
              "cpu": 12,
              "memory": 512,
              "essential":true
            }
          ]
        family: car-sales-ecs-lmap-wamp-cluster-service
        region: eu-north-1
  patches:
  - type: FromCompositeFieldPath
    fromFieldPath: "spec.location"
    toFieldPath: "spec.forProvider.region"
    transforms:
    - type: map
      map:
        EU: "eu-north-1"
        US: "us-east-2"

- name: frontend
  base:
    apiVersion: ecs.aws.upbound.io/v1beta1
    kind: TaskDefinition
    metadata:
      name: car-sales-ecs-taskdefinition-frontend
    spec:
      forProvider:
        containerDefinitions: |-
          [
            {
              "name": "frontend",
              "image": "686255954747.dkr.ecr.eu-north-1.amazonaws.com/car-sales-ecr-lamp-wamp-repository:develop",
              "cpu": 12,
              "memory": 512,
              "essential":true
            }
          ]
        family: car-sales-ecs-lmap-wamp-cluster-service
        region: eu-north-1
  patches:
  - type: FromCompositeFieldPath
    fromFieldPath: "spec.location"
    toFieldPath: "spec.forProvider.region"
    transforms:
    - type: map
      map:
        EU: "eu-north-1"
        US: "us-east-2"

- name: database
  base:
    apiVersion: ecs.aws.upbound.io/v1beta1
    kind: TaskDefinition
    metadata:
      name: car-sales-ecs-taskdefinition-database
    spec:
      forProvider:
        containerDefinitions: |-
          [
            {
              "name": "database",
              "image": "686255954747.dkr.ecr.eu-north-1.amazonaws.com/car-sales-ecr-lamp-wamp-repository:develop",
              "cpu": 12,
              "memory": 512,
              "essential":true
            }
          ]
        family: car-sales-ecs-lmap-wamp-cluster-service
        region: eu-north-1
  patches:
  - type: FromCompositeFieldPath
    fromFieldPath: "spec.location"
    toFieldPath: "spec.forProvider.region"
    transforms:
    - type: map
      map:
        EU: "eu-north-1"
        US: "us-east-2"

- name: webserver
  base:
    apiVersion: ecs.aws.upbound.io/v1beta1
    kind: TaskDefinition
    metadata:
      name: car-sales-ecs-taskdefinition-webserver
    spec:
      forProvider:
        containerDefinitions: |-
          [
            {
              "name": "webserver",
              "image": "686255954747.dkr.ecr.eu-north-1.amazonaws.com/car-sales-ecr-lamp-wamp-repository:develop",
              "cpu": 12,
              "memory": 512,
              "essential":true
            }
          ]
        family: car-sales-ecs-lmap-wamp-cluster-service
        region: eu-north-1
  patches:
  - type: FromCompositeFieldPath
    fromFieldPath: "spec.location"
    toFieldPath: "spec.forProvider.region"
    transforms:
    - type: map
      map:
        EU: "eu-north-1"
        US: "us-east-2"
