---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: car-sales-lamp-wamp-environment
  namespace: prd
spec:
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
    - name: car-sales-ecr-backend-prd-repository #containerRegistries
      base:
        apiVersion: ecr.aws.upbound.io/v1beta1
        kind: Repository
        metadata:
          name: car-sales-ecr-backend-prd-repository
        spec:
          forProvider:
            imageTagMutability: IMMUTABLE
            region: eu-north-1
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.region"
        transforms:
        - type: map
          map:
            EU: "eu-north-1"
            US: "us-east-2"

    - name: car-sales-ecr-frontend-prd-repository #containerRegistries
      base:
        apiVersion: ecr.aws.upbound.io/v1beta1
        kind: Repository
        metadata:
          name: car-sales-ecr-frontend-prd-repository
        spec:
          forProvider:
            imageTagMutability: IMMUTABLE
            region: eu-north-1
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.region"
        transforms:
        - type: map
          map:
            EU: "eu-north-1"
            US: "us-east-2"

    - name: car-sales-ecr-database-prd-repository #containerRegistries
      base:
        apiVersion: ecr.aws.upbound.io/v1beta1
        kind: Repository
        metadata:
          name: car-sales-ecr-database-prd-repository
        spec:
          forProvider:
            imageTagMutability: IMMUTABLE
            region: eu-north-1
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.region"
        transforms:
        - type: map
          map:
            EU: "eu-north-1"
            US: "us-east-2"

    - name: car-sales-ecr-webserver-prd-repository #containerRegistries
      base:
        apiVersion: ecr.aws.upbound.io/v1beta1
        kind: Repository
        metadata:
          name: car-sales-ecr-webserver-repository
        spec:
          forProvider:
            imageTagMutability: IMMUTABLE
            region: eu-north-1
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.region"
        transforms:
        - type: map
          map:
            EU: "eu-north-1"
            US: "us-east-2"

    - name: infrastructure
      base:
        apiVersion: ecs.aws.upbound.io/v1beta1
        kind: Cluster
        metadata:
          name: car-sales-ecs-lmap-wamp-prd-cluster
        spec:
          forProvider:
            region: eu-north-1
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.region"
        transforms:
        - type: map
          map:
            EU: "eu-north-1"
            US: "us-east-2"

    - name: backend
      base:
        apiVersion: ecs.aws.upbound.io/v1beta1
        kind: TaskDefinition
        metadata:
          name: car-sales-ecs-taskdefinition-prd-backend
        spec:
          forProvider:
            containerDefinitions: |-
              [
                {
                  "name": "backend",
                  "image": "686255954747.dkr.ecr.eu-north-1.amazonaws.com/car-sales-ecr-lamp-wamp-repository:main",
                  "cpu": 12,
                  "memory": 512,
                  "essential":true
                }
              ]
            family: car-sales-ecs-lmap-wamp-cluster-service
            region: eu-north-1
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.region"
        transforms:
        - type: map
          map:
            EU: "eu-north-1"
            US: "us-east-2"

    - name: frontend
      base:
        apiVersion: ecs.aws.upbound.io/v1beta1
        kind: TaskDefinition
        metadata:
          name: car-sales-ecs-taskdefinition-prd-frontend
        spec:
          forProvider:
            containerDefinitions: |-
              [
                {
                  "name": "frontend",
                  "image": "686255954747.dkr.ecr.eu-north-1.amazonaws.com/car-sales-ecr-lamp-wamp-repository:main",
                  "cpu": 12,
                  "memory": 512,
                  "essential":true
                }
              ]
            family: car-sales-ecs-lmap-wamp-cluster-service
            region: eu-north-1
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.region"
        transforms:
        - type: map
          map:
            EU: "eu-north-1"
            US: "us-east-2"

    - name: database
      base:
        apiVersion: ecs.aws.upbound.io/v1beta1
        kind: TaskDefinition
        metadata:
          name: car-sales-ecs-taskdefinition-prd-database
        spec:
          forProvider:
            containerDefinitions: |-
              [
                {
                  "name": "database",
                  "image": "686255954747.dkr.ecr.eu-north-1.amazonaws.com/car-sales-ecr-lamp-wamp-repository:main",
                  "cpu": 12,
                  "memory": 512,
                  "essential":true
                }
              ]
            family: car-sales-ecs-lmap-wamp-cluster-prd-service
            region: eu-north-1
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.region"
        transforms:
        - type: map
          map:
            EU: "eu-north-1"
            US: "us-east-2"

    - name: webserver
      base:
        apiVersion: ecs.aws.upbound.io/v1beta1
        kind: TaskDefinition
        metadata:
          name: car-sales-ecs-taskdefinition-prd-webserver
        spec:
          forProvider:
            containerDefinitions: |-
              [
                {
                  "name": "webserver",
                  "image": "686255954747.dkr.ecr.eu-north-1.amazonaws.com/car-sales-ecr-lamp-wamp-repository:main",
                  "cpu": 12,
                  "memory": 512,
                  "essential":true
                }
              ]
            family: car-sales-ecs-lmap-wamp-cluster-prd-service
            region: eu-north-1
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.region"
        transforms:
        - type: map
          map:
            EU: "eu-north-1"
            US: "us-east-2"

    - name: microservice-service
      base:
        apiVersion: ecs.aws.upbound.io/v1beta1
        kind: Service
        metadata:
          name: car-sales-ecs-lmap-wamp-cluster-prd-service
        spec:
          forProvider:
            cluster: car-sales-ecs-prd-cluster
            launchType: EC2
            propagateTags: TASK_DEFINITION
            region: eu-north-1
            taskDefinitionSelector:
              matchLabels:
                testing.upbound.io/example-name: car-sales-ecs-taskdefinition-microservice
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.region"
        transforms:
        - type: map
          map:
            EU: "eu-north-1"
            US: "us-east-2"
  compositeTypeRef:
    apiVersion: batch.blanketops.co.za/v1alpha1
    kind: Environment
