apiVersion: imagebuilder.aws.upbound.io/v1beta1
kind: DistributionConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: imagebuilder/v1beta1/distributionconfiguration
  labels:
    testing.upbound.io/example-name: blanketops-imagebuilder-distribution-configuration
  name: blanketops-imagebuilder-distribution-configuration
spec:
  forProvider:
    distribution:
    - amiDistributionConfiguration:
      - amiTags:
          CostCenter: IT
      region: eu-north-1
    name: BlanketOps
    region: eu-north-1
