---
apiVersion: batch.blanketops.co.za/v1alpha1
kind: Environment
metadata:
  name: car-sales-web-microservices-environment
  namespace: dev
spec:
  location: "EU"
  namespace: dev
  type: microservices

  application:
    name: car-sales-web-microservices-application
    stack:
      name: microservices
      tier:
        name: backend
        programmingLanguageName: c#

  deployment:
    name: car-sales-web-microservices-deployment
    strategy: canary
    scheduleType: manual

  infrastructure:
    clusterName: blanketops-ecs-cluster
    region: eu-north-1

  capacity:
    scalingOperationName: blanketops-microservices-capacity-scaling-operation
    scaling: blanketops-microservices-capacity-scaling
    scalingGroupName: blanketops-aws-autoscaling-group
    clusterName: blanketops-aws-ecs-cluster
    capacityProvider: blanketops-ecs-capacity-provider
    clusterCapacityProviders: blanketops-ecs-capacity-providers

  containerRegistries:
  - name: blanketops-ecr-microservice-repository
    region: eu-north-1
    imageTagMutability: MUTABLE

  microservices:
  - name: car-sales-web-microservice
    image: 686255954747.dkr.ecr.eu-north-1.amazonaws.com/blanketops-ecr-microservice-repository:feature#hello-world
    labels:
      app: app
      tier: microservice
    size: 1
