---
apiVersion: batch.blanketops.co.za/v1alpha1
kind: Environment
metadata:
  name: car-sales-web-microservices-environment
  namespace: dev
spec:
  location: "EU"
  namespace: dev
  type: microservices

  application:
    name: car-sales-web-microservices-application
    stack:
      name: microservices
      tier:
        name: backend
        programmingLanguageName: c#

  deployment:
    name: car-sales-web-microservices-deployment
    strategy: canary #
    scheduleType: manual #

  infrastructure:
    clusterName: car-sales-web-microservice-cluster #

  capacity:
    scalingOperationName: blanketops-microservices-capacity-scaling-operation #
    scaling: blanketops-microservices-capacity-scaling #
    scalingGroupName: blanketops-aws-autoscaling-group #
    capacityProvider: car-sales-ecs-capacity-provider ##
    clusterCapacityProviders: car-sales-ecs-cluster-capacity-providers ##

  containerRegistries:
  - name: car-sales-ecr-microservice-repository
    imageTagMutability: MUTABLE

  microservices:
  - name: car-sales-ecs-taskdefinition-microservice
    image: 686255954747.dkr.ecr.eu-north-1.amazonaws.com/blanketops-ecr-microservice-repository:feature#hello-world
    labels:
      app: app
      tier: microservice
    size: 1
