---
apiVersion: batch.blanketops.co.za/v1alpha1
kind: Environment
metadata:
  name: car-sales-web-microservices-environment
  namespace: dev
spec:
  application:
    name: car-sales-web-microservices-application
    stack:
      name: microservices
      tier:
        name: backend
        programmingLanguageName: c#
  builder:
    name: car-sales-web-microservices-build
    imageToBuild: public.ecr.aws/docker/library/httpd:latest
    scheduleType: manual
  capacity:
    scalingOperationName: car-sales-microservices-capacity-scaling-operation #
    scaling: car-sales-microservices-capacity-scaling #
    scalingGroupName: car-sales-aws-autoscaling-group #
    capacityProvider: car-sales-ecs-capacity-provider ##
    clusterCapacityProviders: car-sales-ecs-cluster-capacity-providers ##
  containerRegistries:
  - name: car-sales-ecr-microservice-repository
    imageTagMutability: MUTABLE
  deployment:
    name: car-sales-web-microservices-deployment
    strategy: canary #
    scheduleType: manual #
  infrastructure:
    clusterName: car-sales-web-microservice-cluster #
  location: "EU"
  namespace: dev
  microservices:
  - name: car-sales-ecs-taskdefinition-microservice
    image: 686255954747.dkr.ecr.eu-north-1.amazonaws.com/car-sales-ecr-microservice-repository:feature#hello-world
    containerPort: 80
    labels:
      app: app
      tier: microservice
    size: 1
  type: microservices
