apiVersion: pt.fn.crossplane.io/v1beta1
kind: Resources
resources:
- name: car-sales-web-microservice-cluster #microservice #Environment Type, spec
  base:
    apiVersion: ecs.aws.upbound.io/v1beta1
    kind: Cluster
    metadata:
      name: car-sales-web-microservice-cluster
      labels:
        testing.upbound.io/example-name: car-sales-web-microservice-cluster
    spec:
      forProvider:
        region: eu-north-1
  patches:
  - type: FromCompositeFieldPath
    fromFieldPath: "spec.location"
    toFieldPath: "spec.forProvider.region"
    transforms:
    - type: map
      map:
        EU: "eu-north-1"
        US: "us-east-2"
