apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: single
  namespace: dev
spec:
  tag: 686255954747.dkr.ecr.eu-north-1.amazonaws.com/blanketops-ecr-single-repository:develop
  serviceAccount: single-service-account
  builder:
    name: single-image-builder
    kind: Builder
  source:
    git:
      url: git@github.com:blanketops/blanketops-nginx-example.git
      revision: refs/heads/develop
