---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: car-sales-microservice-environment
spec:
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: application
        base:
          apiVersion: dynamodb.aws.upbound.io/v1beta1
          kind: Table
          metadata:
            name: car-sales-web-microservice-application
          spec:
            forProvider:
              region: "us-east-2"
              writeCapacity: 10
              readCapacity: 10
              attribute:
              - name: name
                type: S
              hashKey: name

        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.location"
          toFieldPath: "spec.forProvider.region"
          transforms:
          - type: map
            map:
              EU: "eu-north-1"
              US: "us-east-2"
      # - name: containerRegistries
      #   base:
      #     apiVersion: ecr.aws.upbound.io/v1beta1
      #     kind: Repository
      #     metadata:
      #       name: blanketops-ecr-microservice-repository
      #     spec:
      #       forProvider:
      #         imageTagMutability: MUTABLE
      #         region: eu-north-1
      #   patches:
      #   - type: FromCompositeFieldPath
      #     fromFieldPath: "spec.location"
      #     toFieldPath: "spec.forProvider.region"
      #     transforms:
      #     - type: map
      #       map:
      #         EU: "eu-north-1"
      #         US: "us-east-2"
      # - name: infrastructure
      #   base:
      #     apiVersion: ecs.aws.upbound.io/v1beta1
      #     kind: Cluster
      #     metadata:
      #       name: blanketops-ecs-cluster
      #     spec:
      #       forProvider:
      #         region: eu-north-1
      #   patches:
      #   - type: FromCompositeFieldPath
      #     fromFieldPath: "spec.location"
      #     toFieldPath: "spec.forProvider.region"
      #     transforms:
      #     - type: map
      #       map:
      #         EU: "eu-north-1"
      #         US: "us-east-2"
      # - name: capacityProvider
      #   base:
      #     apiVersion: ecs.aws.upbound.io/v1beta1
      #     kind: CapacityProvider
      #     metadata:
      #       annotations:
      #       meta.upbound.io/example-id: ecs/v1beta1/capacityprovider
      #     labels:
      #       testing.upbound.io/example-name: blanketops-ecs-capacity-provider
      #     name: blanketops-ecs-capacity-provider
      #     spec:
      #       forProvider:
      #         autoScalingGroupProvider:
      #         - autoScalingGroupArnSelector:
      #             matchLabels:
      #               testing.upbound.io/example-name: blanketops-autoscaling-group
      #           managedScaling:
      #           - maximumScalingStepSize: 1000
      #             minimumScalingStepSize: 1
      #             status: ENABLED
      #             targetCapacity: 10
      #           managedTerminationProtection: DISABLED
      #         region: eu-north-1
      #   patches:
      #   - type: FromCompositeFieldPath
      #     fromFieldPath: "spec.location"
      #     toFieldPath: "spec.forProvider.region"
      #     transforms:
      #     - type: map
      #       map:
      #         EU: "eu-north-1"
      #         US: "us-east-2"
      # - name: clusterCapacityProviders
      #   base:
      #     apiVersion: ecs.aws.upbound.io/v1beta1
      #     kind: ClusterCapacityProviders
      #     metadata:
      #       labels:
      #       testing.upbound.io/example-name: blanketops-ecs-cluster-capacity-providers
      #     name: blanketops-ecs-cluster-capacity-providers
      #     spec:
      #       forProvider:
      #         capacityProviders:
      #         - EC2
      #         clusterNameSelector:
      #           matchLabels:
      #             testing.upbound.io/example-name: blanketops-ecs-cluster
      #         defaultCapacityProviderStrategy:
      #         - base: 1
      #           capacityProvider: EC2
      #           weight: 100
      #         region: eu-north-1
      #   patches:
      #   - type: FromCompositeFieldPath
      #     fromFieldPath: "spec.location"
      #     toFieldPath: "spec.forProvider.region"
      #     transforms:
      #     - type: map
      #       map:
      #         EU: "eu-north-1"
      #         US: "us-east-2"
  compositeTypeRef:
    apiVersion: batch.blanketops.co.za/v1alpha1
    kind: Environment
