---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: environments.batch.blanketops.co.za
spec:
  group: batch.blanketops.co.za
  names:
    kind: Environment
    plural: environments
  claimNames:
    kind: EnvironmentClaim
    plural: environmentclaim
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              application:
                name:
                  type: string
                type: object
                properties:
                stack:
                  name:
                    type: string
                  tier:
                    type: object
                    properties:
                      name:
                        type: string
                      programmingLanguageName:
                        type: string
            required:
            - name
