apiVersion: repositories.argocd.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: example-scoped-project.git
spec:
  forProvider:
    passwordRef:
      key: token
      name: example-project.git
      namespace: crossplane-system
    project: example-project
    repo: git@github.com:blanketops/blanketops-cloud-native-manifests.git
    type: git
    username: example-user
  providerConfigRef:
    name: argocd-provider
