apiVersion: sqs.aws.upbound.io/v1beta1
kind: QueuePolicy
metadata:
  annotations:
    meta.upbound.io/example-id: sqs/v1beta1/queue-policy
  labels:
    testing.upbound.io/example-name: blanketops-sqs-queue-policy
  name: blanketops-sqs-queue-policy
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "example",
            "Effect": "Allow",
            "Principal": {
              "Service": "s3.amazonaws.com"
            },
            "Action": "sqs:SendMessage",
            "Resource": "arn:aws:sqs:eu-north-1:*:blanketops-sqs-queue"
          }
        ]
      }
    queueUrlSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-sqs-queue
    region: eu-north-1
