apiVersion: containerregistry.azure.upbound.io/v1beta1
kind: Webhook
metadata:
  name: example
spec:
  forProvider:
    actions:
    - push
    customHeaders:
      Content-Type: application/json
    location: East US
    registryName: upbound
    resourceGroupNameRef:
      name: example-containerreg
    scope: mytag:*
    serviceUri: https://mywebhookreceiver.example/mytag
    status: enabled
