apiVersion: containerregistry.azure.upbound.io/v1beta1
kind: Registry
metadata:
  name: upbound
spec:
  forProvider:
    adminEnabled: false
    dataEndpointEnabled: true
    georeplications:
    - location: East US
      tags: {}
      zoneRedundancyEnabled: true
    location: West Europe
    resourceGroupNameRef:
      name: example-containerreg
    sku: Premium
---
apiVersion: containerregistry.azure.upbound.io/v1beta1
kind: Registry
metadata:
  annotations:
    meta.upbound.io/example-id: containerregistry/v1beta1/tokenpassword
  labels:
    testing.upbound.io/example-name: tokenpasswordregistry
  name: tokenpasswordregistry
spec:
  forProvider:
    adminEnabled: false
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: tokenpassword-rg
    sku: Premium
