apiVersion: containerregistry.azure.upbound.io/v1beta1
kind: TokenPassword
metadata:
  annotations:
    meta.upbound.io/example-id: containerregistry/v1beta1/tokenpassword
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    containerRegistryTokenIdSelector:
      matchLabels:
        testing.upbound.io/example-name: tokenpasswordtoken
    password1:
    - expiry: 2024-03-22T17:57:36+08:00
