apiVersion: containerregistry.azure.upbound.io/v1beta1
kind: Token
metadata:
  name: example
spec:
  forProvider:
    containerRegistryName: upbound
    resourceGroupNameRef:
      name: example-containerreg
    scopeMapIdRef:
      name: example

---
apiVersion: containerregistry.azure.upbound.io/v1beta1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: containerregistry/v1beta1/tokenpassword
  labels:
    testing.upbound.io/example-name: tokenpasswordtoken
  name: tokenpasswordtoken
spec:
  forProvider:
    containerRegistryNameSelector:
      matchLabels:
        testing.upbound.io/example-name: tokenpasswordregistry
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: tokenpassword-rg
    scopeMapIdSelector:
      matchLabels:
        testing.upbound.io/example-name: tokenpasswordsm

---
apiVersion: containerregistry.azure.upbound.io/v1beta1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: containerregistry/v1beta2/tokenpassword
  labels:
    testing.upbound.io/example-name: tokenpasswordtoken
  name: tokenpasswordtoken
spec:
  forProvider:
    containerRegistryNameSelector:
      matchLabels:
        testing.upbound.io/example-name: tokenpasswordregistry
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: tokenpassword-rg
    scopeMapIdSelector:
      matchLabels:
        testing.upbound.io/example-name: tokenpasswordsm
