apiVersion: containerregistry.azure.upbound.io/v1beta1
kind: AgentPool
metadata:
  name: example
spec:
  forProvider:
    containerRegistryName: upbound
    location: West Europe
    resourceGroupNameRef:
      name: example-containerreg
