apiVersion: dashboard.jenkins.crossplane.io/v1alpha1
kind: Job
metadata:
  name: job-example
spec:
  forProvider:
    config: >-
      <?xml version="1.1" encoding="UTF-8"?><project>
        <description/>
        <keepDependencies>false</keepDependencies>
        <properties/>
        <scm class="hudson.scm.NullSCM"/>
        <canRoam>true</canRoam>
        <disabled>false</disabled>
        <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
        <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
        <triggers/>
        <concurrentBuild>false</concurrentBuild>
        <builders/>
        <publishers/>
        <buildWrappers/>
      </project>
    name: Jan27Test1
    parent: Testf
  providerConfigRef:
    name: provider-jenkins-config
