apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: wordpress-example
spec:
  forProvider:
    chart:
      name: wordpress
      repository: https://charts.bitnami.com/bitnami
      version: 15.2.5
    namespace: wordpress
    set:
    - name: param1
      value: value2
    values:
      service:
        type: ClusterIP
  providerConfigRef:
    name: helm-provider
