apiVersion: kms.aws.upbound.io/v1beta1
kind: Grant
metadata:
  name: blanketops-kms-grant
spec:
  forProvider:
    constraints:
    - encryptionContextEquals:
        Department: Finance
    granteePrincipalSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-kms-principal
    keyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-kms-key
    name: blanketops-kms-grant
    operations:
    - Encrypt
    - Decrypt
    - GenerateDataKey
    region: eu-north-1
