apiVersion: applicationsets.argocd.crossplane.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-ref
spec:
  forProvider:
    generators:
    - list:
        elements:
        - cluster: engineering-dev
        - cluster: engineering-prod
    template:
      metadata:
        name: "{{cluster}}-guestbook"
      spec:
        destination:
          nameSelector:
            matchLabels:
              purpose: dev
          namespace: guestbook-{{cluster}}
        project: default
        source:
          path: applicationset/examples/list-generator/guestbook/{{cluster}}
          repoURL: https://github.com/argoproj/argo-cd.git
          targetRevision: HEAD
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
          - CreateNamespace=true
  providerConfigRef:
    name: argocd-provider
