apiVersion: applications.argocd.crossplane.io/v1alpha1
kind: Application
metadata:
  name: blanketops-argocd-application
spec:
  forProvider:
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: default
    source:
      path: /
      repoURL: https://github.com/blanketops/blanketops-environments-min.git
      targetRevision: develop
  providerConfigRef:
    name: default
