apiVersion: projects.argocd.crossplane.io/v1alpha1
kind: Project
metadata:
  name: blanketops-argocd-project
spec:
  forProvider:
    projectLabels:
      argocd.crossplane.io/global-project: "true"
  providerConfigRef:
    name: blanketops-argocd
