apiVersion: v1
kind: Secret
metadata:
  name: blanketops-cloud-native-manifests-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/blanketops/blanketops-cloud-native-manifests.git
