apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: trigger-github-issue
spec:
  triggers:
  - name: github-listener
    interceptors:
    - ref:
        name: "github"
        kind: ClusterInterceptor
        apiVersion: triggers.tekton.dev
      params:
      - name: "secretRef"
        value:
          secretName: tekton-triggers-issue-secret
          secretKey: token
      - name: "eventTypes"
        value: [ "issue" ]
  bindings:
  - ref: pipeline-binding
  template:
    ref: pipeline-template
