apiVersion: acmpca.aws.upbound.io/v1beta1
kind: Certificate
metadata:
  name: blanketops-acmpa-certificate
spec:
  forProvider:
    certificateAuthorityArnRef:
      name: blanketops-acmpa-certificate-authority
    certificateSigningRequestSecretRef:
      key: certificate_signing_request
      name: blanketops-acmpca-ca
      namespace: upbound-system
    region: eu-north-1
    signingAlgorithm: SHA256WITHRSA
    templateArn: arn:aws:acm-pca:::template/RootCACertificate/V1
    validity:
    - type: YEARS
      value: "1"
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: balnketops-acmpca-certificate
    namespace: upbound-system
