apiVersion: pt.fn.crossplane.io/v1beta1
kind: Resources
resources:
- name: car-sales-web-lmap-wamp
  base:
    apiVersion: ecs.aws.upbound.io/v1beta1
    kind: TaskDefinition
    metadata:
      name: car-sales-ecs-taskdefinition-lmap-wamp
      labels:
        testing.upbound.io/example-name: car-sales-ecs-taskdefinition-lmap-wamp
    spec:
      forProvider:
        containerDefinitions: |-
          [
            {
              "name": "lmap-wamp",
              "image": "public.ecr.aws/docker/library/httpd:latest",
              "cpu": 12,
              "memory": 512,
              "essential":true,
              "executionRoleArn": "arn:aws:iam::686255954747:role/ecsTaskRole",
              "networkMode": "awsvpc",
              "entryPoint": [
                 "sh",
                 "-c"
               ],
                "portMappings": [
                  {
                    "containerPort": 80,
                    "hostPort": 80,
                    "protocol": "tcp"
                  }
                ]
            }
          ]
        family: car-sales-ecs-taskdefinition-lmap-wamp
        region: eu-north-1

  patches:
  - type: FromCompositeFieldPath
    fromFieldPath: "spec.location"
    toFieldPath: "spec.forProvider.region"
    transforms:
    - type: map
      map:
        EU: "eu-north-1"
        US: "us-east-2"
