apiVersion: sources.knative.dev/v1alpha1
kind: GitHubSource
metadata:
  name: github-source-create
spec:
  eventTypes:
  - create
  ownerAndRepository: blanketops/blanketops-nginx-example
  accessToken:
    secretKeyRef:
      name: github-source-create-secret
      key: accessToken
  secretToken:
    secretKeyRef:
      name: github-source-create-secret
      key: secretToken
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: github-message-dumper
