apiVersion: route53.aws.upbound.io/v1beta1
kind: TrafficPolicy
metadata:
  labels:
    testing.upbound.io/example-name: blanketops-route53-traffic-policy
  name: blanketops-route53-traffic-policy
spec:
  forProvider:
    comment: example comment
    document: |
      {
        "AWSPolicyFormatVersion": "2015-10-01",
        "RecordType": "A",
        "Endpoints": {
          "endpoint-start-NkPh": {
            "Type": "value",
            "Value": "10.0.0.2"
          }
        },
        "StartEndpoint": "endpoint-start-NkPh"
      }
    name: blanketops-route53-traffic-policy
    region: eu-north-1
