apiVersion: inspector.aws.upbound.io/v1beta1
kind: AssessmentTarget
metadata:
  annotations:
    meta.upbound.io/example-id: inspector/v1beta1/assessmenttarget
  labels:
    testing.upbound.io/example-name: blanketops-inspector-assessment-target
  name: blanketops-inspector-assessment-target
spec:
  forProvider:
    name: default
    region: eu-north-1
