apiVersion: compute.gcp.upbound.io/v1beta1
kind: Address
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/serviceattachment
  labels:
    testing.upbound.io/example-name: service-attachment
  name: service-attachment
spec:
  forProvider:
    addressType: INTERNAL
    region: us-central1
    subnetworkSelector:
      matchLabels:
        testing.upbound.io/example-name: service-attachment
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Address
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/address
  labels:
    testing.upbound.io/example-name: example_ip_address_with_network
  name: example-ip-address-with-network
spec:
  forProvider:
    address: 10.0.42.42
    addressType: INTERNAL
    region: us-central1
    subnetworkSelector:
      matchLabels:
        testing.upbound.io/example-name: example_ip_address_subnet
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Address
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/vpntunnel
  labels:
    testing.upbound.io/example-name: vpn-tunnel
  name: vpn-tunnel
spec:
  forProvider:
    region: us-central1
