apiVersion: compute.gcp.upbound.io/v1beta1
kind: AttachedDisk
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/attacheddisk
  labels:
    testing.upbound.io/example-name: attached-disk
  name: attached-disk
spec:
  forProvider:
    diskSelector:
      matchLabels:
        testing.upbound.io/example-name: attached-disk
    instanceSelector:
      matchLabels:
        testing.upbound.io/example-name: attached-disk
    zone: us-central1-a
