apiVersion: compute.gcp.upbound.io/v1beta1
kind: Autoscaler
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/autoscaler
  labels:
    testing.upbound.io/example-name: autoscaler
  name: autoscaler
spec:
  forProvider:
    autoscalingPolicy:
    - cooldownPeriod: 60
      maxReplicas: 2
      minReplicas: 1
    targetSelector:
      matchLabels:
        testing.upbound.io/example-name: autoscaler
    zone: us-central1-a
