apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendService
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/urlmap
  labels:
    testing.upbound.io/example-name: urlmap
  name: urlmap
spec:
  forProvider:
    healthChecksSelector:
      matchLabels:
        testing.upbound.io/example-name: urlmap
    portName: http
    protocol: HTTP
    timeoutSec: 10
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendService
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/globalforwardingrule
  labels:
    testing.upbound.io/example-name: global-forwarding-rule
  name: global-forwarding-rule
spec:
  forProvider:
    backend:
    - balancingMode: UTILIZATION
      capacityScaler: 1
      groupSelector:
        matchLabels:
          testing.upbound.io/example-name: global-forwarding-rule
      maxUtilization: 1
    healthChecksRefs:
    - name: global-forwarding-rule
    loadBalancingScheme: EXTERNAL
    portName: tcp
    protocol: SSL
    timeoutSec: 10
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendService
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/targettcpproxy
  labels:
    testing.upbound.io/example-name: target-tcp-proxy
  name: target-tcp-proxy
spec:
  forProvider:
    healthChecksRefs:
    - name: target-tcp-proxy
    protocol: TCP
    timeoutSec: 10
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendService
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/backendservice
  labels:
    testing.upbound.io/example-name: backend-service
  name: backend-service
spec:
  forProvider:
    healthChecksSelector:
      matchLabels:
        testing.upbound.io/example-name: backend-service
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendService
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/targetsslproxy
  labels:
    testing.upbound.io/example-name: target-ssl-proxy
  name: target-ssl-proxy
spec:
  forProvider:
    healthChecksRefs:
    - name: target-ssl-proxy
    protocol: SSL
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendService
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/backendservicesignedurlkey
  labels:
    testing.upbound.io/example-name: example_backend
  name: backend-service
spec:
  forProvider:
    healthChecksSelector:
      matchLabels:
        testing.upbound.io/example-name: backend-service
