apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendServiceSignedURLKey
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/backendservicesignedurlkey
  labels:
    testing.upbound.io/example-name: backend_key
  name: backend-key
spec:
  forProvider:
    backendServiceSelector:
      matchLabels:
        testing.upbound.io/example-name: example_backend
    keyValueSecretRef:
      key: attribute.b64_url
      name: backend-service-signed-url-key-id
      namespace: upbound-system
    name: test-key
