apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendBucket
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/targetgrpcproxy
  labels:
    testing.upbound.io/example-name: target-grpc-proxy
  name: target-grpc-proxy
spec:
  forProvider:
    bucketNameSelector:
      matchLabels:
        testing.upbound.io/example-name: target-grpc-proxy
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendBucket
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/urlmap
  labels:
    testing.upbound.io/example-name: urlmap
  name: urlmap
spec:
  forProvider:
    bucketNameSelector:
      matchLabels:
        testing.upbound.io/example-name: urlmap
    enableCdn: true
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendBucket
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/targethttpsproxy
  labels:
    testing.upbound.io/example-name: target-https-proxy
  name: target-https-proxy
spec:
  forProvider:
    bucketNameSelector:
      matchLabels:
        testing.upbound.io/example-name: target-https-proxy
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendBucket
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/backendbucket
  labels:
    testing.upbound.io/example-name: backend-bucket
  name: backend-bucket
spec:
  forProvider:
    bucketNameSelector:
      matchLabels:
        testing.upbound.io/example-name: backend-bucket
    description: Contains beautiful images
    enableCdn: true
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendBucket
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/targethttpproxy
  labels:
    testing.upbound.io/example-name: target-http-proxy
  name: target-http-proxy
spec:
  forProvider:
    bucketNameSelector:
      matchLabels:
        testing.upbound.io/example-name: target-http-proxy
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendBucket
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/backendbucket
  labels:
    testing.upbound.io/example-name: backend-bucket-signed-url-key
  name: backend-bucket-random
spec:
  forProvider:
    bucketNameSelector:
      matchLabels:
        testing.upbound.io/example-name: backend-bucket-signed-url-key
