apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendBucketSignedURLKey
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/backendbucketsignedurlkey
  labels:
    testing.upbound.io/example-name: backend-bucket-signed-url-key
  name: backend-bucket-signed-url-key
spec:
  forProvider:
    backendBucketSelector:
      matchLabels:
        testing.upbound.io/example-name: backend-bucket-signed-url-key
    keyValueSecretRef:
      key: attribute.b64_url
      name: backend-bucket-signed-url-key-id
      namespace: upbound-system
    name: backend-bucket-signed-url-key
