apiVersion: compute.gcp.upbound.io/v1beta1
kind: DiskResourcePolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/diskresourcepolicyattachment
  labels:
    testing.upbound.io/example-name: disk-resource-policy-attachment
  name: disk-resource-policy-attachment
spec:
  forProvider:
    diskSelector:
      matchLabels:
        testing.upbound.io/example-name: disk-resource-policy-attachment
    nameSelector:
      matchLabels:
        testing.upbound.io/example-name: disk-resource-policy-attachment
    zone: us-central1-a
