apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: car-sales-web-mobile-prd-environment
  namespace: argocd
  labels:
    name: car-sales-web-mobile-prd-environment
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: HookFailed
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: blanketops-environments-min-argocd-project
  sources:
  - repoURL: https://github.com/blanketops/blanketops-environments-min.git #xRD,#Comp/.\Env
    path: environments/mobile/prd
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=false
  revisionHistoryLimit: 1000
