---
apiVersion: ecs.aws.upbound.io/v1beta1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/service
  name: car-sales-web-microservices-deployment
spec:
  forProvider:
    clusterSelector:
      matchLabels:
        testing.upbound.io/example-name: car-sales-web-microservice-cluster
    launchType: EC2
    propagateTags: TASK_DEFINITION
    region: eu-north-1
    taskDefinitionSelector:
      matchLabels:
        testing.upbound.io/example-name: car-sales-ecs-taskdefinition-microservice
