apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener-issue
spec:
  triggerGroups:
  - name: github-issue-group
    interceptors:
    - name: "validate GitHub payload and filter on eventType"
      ref:
        name: "github"
      params:
      - name: "secretRef"
        value:
          secretName: github-secret
          secretKey: secretToken
      - name: "eventTypes"
        value: [ "issue" ]
    triggerSelector:
      labelSelector:
        matchLabels:
          type: github-pr
