apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: secret-inventory-remote-debug
spec:
  forProvider:
    inventories:
    - secretRef:
        key: hosts
        name: inventory
        namespace: crossplane-system
      source: Secret
    playbookInline: |
      ---
      - hosts: all
        tasks:
          - name: ansibleplaybook-simple
            debug:
              msg: Your are running 'ansibleplaybook-simple' example
