apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  annotations:
    ansible.crossplane.io/runPolicy: ObserveAndDelete
  name: gcpbucket
spec:
  forProvider:
    playbookInline: |
      ---
      - hosts: localhost
        pre_tasks:
          - name: Install requests python package on version 2.28.1
            ansible.builtin.pip:
              name: requests==2.28.1
              extra_args: --user
          - name: Install google-auth python package on version 2.12.0
            ansible.builtin.pip:
              name: google-auth==2.12.0
              extra_args: --user
        tasks:
          - name: create a gcp bucket
            google.cloud.gcp_storage_bucket:
              # please make sure that name is unique
              name: ansible-storage-module
              project: test-project
              auth_kind: serviceaccount
              service_account_file: gcp-credentials.json
              state: present
            when: ansible_provider_meta.gcpbucket.state == 'present'
  providerConfigRef:
    name: default
